behaviors:
  SudokuAgent:  # Nazwa agenta
    trainer_type: ppo  # Typ trenera (Proximal Policy Optimization)
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      num_layers: 2
      hidden_units: 128
      normalize: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000  # Maksymalna liczba kroków treningowych
    time_horizon: 64
    summary_freq: 10000  # Częstotliwość zapisywania statystyk